version: "2.0"

services:
    mysql:
        image: "mysql:5.7"
        volumes:
            - ./data/:/data
            - ./init.sh:/docker-entrypoint-initdb.d/a_init.sh
        ports: 
            - 3306:3306
        environment:    
            - MYSQL_ROOT_PASSWORD=secret
            - MYSQL_DATABASE=tests

